---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: capoaberto-api-brasil
  namespace: capoaberto-staging
spec:
  encryptedData:
    API_BRASIL_BEARER_TOKEN: AgBxqphpLo8WByivqD2l+eQg5buWsQ2fdehJW5mHtFgc6RLuz8YuHwpEb/6Vim8uHLryW3d6vppjmQd2OCG0EkKQHuYHEHxToluwFybBTObauyVVNuIbGneIs4N1kB2gKOL2j6PaFHjCbSStv3X1PoewTYq0A8BN4cmJeQheu+Mio0eit+ZLxHbyt0U4+kNaUtOKvWmA1sIjwEQaZDbVZLogtbbMddVL0H69JP8F7rBZvmxELO/YBVMPfJDbdtv/NDeCK2nDE8U9YVVoz33p/XsNfxc8fMCSKr/oPjW2l7hhs8O30iN5iZwoc1oB/pqPFzZRtS2ETQSUWA3y/n6ExNd2yDVWKyKPbB7h2OABIuVOg1MBvFhW8+oxQ7XqKluiWjied9qLHVMURaFpmGm2lhYfVy6w237QKakIP3jFL7Wy5/aUWuw0MClK8ljMONkhqIFcIPzky7nb44/AcwJf1P3zH16PXgMM4fH8lxRHnJP70LXgC2flslfGT7VODHWqgWwAw0wswClDJ6AS7g/MhaE5qUMXJ7WNyY1kiDitlN/mO0Xu7TjrjGl73ph+c2Rk4v27DVs94ciqxPxxaTazUwBuw7p9A9BzK4Talu2xpkXlyvhm3Iehx6diLv4f5q13qchFSIgapmatQClJfWIEyPfVhws6uMiKgPXwzbKqVCQLg59j7QnbaWyW+eV6+ED4ofcSKtRB+BaEkytT2eQ/B+gMdJ8kVqrGJAHwnq/NuvpDo3LIa1fyETSfALiow6ldkTCnWkNG/wmwdF1MCNweStRvdcb39KXKPxmCEfe6RPwpLc+Qb0dVPSvORh38BcOMk4RYJMt9iDZMDRwwi+cNQ8UpNXJh6e7UMXTVUcdCJWiFhpepmVH1Dbm+PL/BHPIZKT+G5acuSQMvUDKAwxMPFC4Zq0y7IHvzqoF7Dc06rovOy/RPfpMqOhjSh6iOwU+xNgHTjmFnN/0Awmf8TCxUUGN3gR/epAucVmK5MctCnLneLbPn3YWluo4BPQVRvvvPMmObMBfSjRZBTXg8ugZtPxS06sJVLLXnaije7hi9XsZ8fu9O3FnMvQfcgobbaHizS8SVidTohwXVYyEAkz28C63xyrujw9NWHHIIUqxklTFXGnZwBmI9DZfNnLZ8OtaG7Q==
  template:
    metadata:
      creationTimestamp: null
      name: capoaberto-api-brasil
      namespace: capoaberto-staging
    type: Opaque
