---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: capoaberto-asaas
  namespace: capoaberto
spec:
  encryptedData:
    ASAAS_API_KEY: AgA5d1xz8SSH0OZgeKdpJo5DxyD6bxKtYNcynYFEG72s+A38mEV+wLTq3zZiUy1pzvhxWfp0xtx38fE99R2130NjRr4Uot9CxIl9OonsJRHyV0zlPdoJQWtVbUPRedy1u8boZTGmSptdHUl7u+ziXmn099lVlb+LD4FF2x75uIf7FPpObBH/hrmA1NxBb0smFO+Zwozo4TPgc0X08HtQGalBijB29Rnr5CIjK1VmPKSfH51MmNMMGRrScLFyFCOlkBWwfFWBcjop6BeSJqKHVke0ovW1oa3yU6VNFzYBBPdDl2ZhttRh2JNIDjOaMJXYaT4Yq44pE2bWGKMNtzE2k+TZHWdMFqz2D2RJPzr1ZivUiTg2v+/jCPOUWaqkoPa73Ep+vxWz5EJZDN9SrDC9eUuxSVkxFV73ukNJ+tmGNPvD32+SqzdW5rTvHBj4x/2rm0aT+PfzDteL7nVWEqZmMIfEfNufwJbseusu/bdch+KnwoUtWfz4Pd3sa1ALksr6EJx96zOoCy7l+wR6cU/V4//DQmC3pJF1Jidyj5kTlr4iME0PWMppPi+6AJ9f1RslEHBbOkivJMOS62xiSRyMC0c6JcJrSAMbxtAsTHoYDFdqw+KIMXd/hUIMyGXgAi0E35wDCbRcPBTGl2t7n+nYyZHl2wnY89ZbQiO5JBQFHhTU3v0yE313zV7UnwU//m3SLMXphUbBhVm1Lk3s15UzBYI8TpVq3Oxcd4eZZ8j6bWNHsmE5D6YOlah6w4Vj4GA8/N/OuNi7LHD2P06IAu79hPNehMMAnXd2AgU/ZmStcsoGaMuBeh64gY+W4lCJoc1oR3MzDSE8eKsdzoFO184cWzqO+Jj7Y+c4UC8V3hhrKXcIZzXX4Dj7y+TUxcp6YqqvfnS6gJmkAObdJ9j3Fh/MoXxZeRuXLoMD
    ASAAS_WEBHOOK_AUTH_TOKEN: AgBHZl61JFH4ms/kPfrWB5smC+jYZnuE01H3YZiHQlygxye5p9yUuZi7gC0ymyggFC7w189XI5AG6uTKnzOtd+uoUUOgrzYTEb4M4/jXtiCY80qb1H+Lz2mcvJrdFh0FUGW9X6jB8Wg/Silu2iItBJWT6Aw3KR5TGED42iIBTz42wnHN9/sIUexZEzBmjKfU6eS0yY+IyXj6CBVYRUJhOdC/THY+eaEK3AnkZLEKSYnY3uUnpCK6943X2LrjpCR2wZj3uPYtd95xavh/jam48vXjkoaJRc9HGL62Tx8xiA74Q2MeXs3y4MMoLQHaKqyj675V5hqKcDlhmTBeQcsZOAaOI5OfHLawbGLrNHnofqtfa27UJFeEB5d2jvS6yWq67V12hoY3UewAi2KZkC5iBw1SKG3omo7hfH4wSG6fIt/beL38Dlyy4BZ0nU//2ghb0OOzeDiWBVC5IlPfwwAvXZzJwvnU+E6Sz5UkzJ76R0/08sUDnezHP8jFeMOjButroJh6J8V4BeOc5X5XZvPHi40lLlNBWSCbi6twXmhk85d0oEjEdv85ZFkAx3T1s0QM6FcUJZCpCu1m3cDozxym23b9aEPnM2CHxle8LwfY14Scf3Q7+lwHvZ9oYxawHO7aHdMYPwcr6S+LNLoR0CrAX7KTiwErQzm4z1NRyIXuD8toAboa8uG9nzhr6qP5S1TPkMQOoHdktGfdTrCdFzBTbh9AKL4vX0dgCgFiXQM+tX0oE515xc8ntnmLVgqqv322KkpYLcCbCGHS9j02pUVuEROg
  template:
    metadata:
      creationTimestamp: null
      name: capoaberto-asaas
      namespace: capoaberto
