---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: capoaberto-asaas
  namespace: capoaberto
spec:
  encryptedData:
    ASAAS_API_KEY: AgCAGNSkVYXXrJrMeLp0lLLDucHO2pSLUd2Of1qY2aabaNyJ4450FLHqjZMqe6cSqdpPkunwQl9sz7TOqz/BXh3fcCYgHlchD2pPxyqJigZ44g+Ru9QcPauw5ldSOvHg8PyGBDoNl09YKauQxU8uHyRG2FbSn3pfDyO62Txr16JNNfuq0PF0553Ij7/E4CBb7XF9AxcTjkRzFSAL1GFTIyP5oenKrplrxkO+h6X60hTTMOp6yRrJtRvHr9LFSYMe/cWK6c65+w3GmSKkhKoCyzvGakVh6qE6mxTsIpWYtw6q9O697FA2rMYQWYZyXfUt1EPD/ir8TVqmd8EJ1NOJS72PMz8TlswuQcmBh5SgTct4ftHlaO6etKCMEgxWyuO88LGs+URUaU2GtcsdgnvpUF2jhtPwuBq1Tanj8PzvnmjTbENzb5Xd9uUPEiUJLHVqrErG9ZhWWaxX1hF6NOTBMdWyIvgqSveYrnjynw/mbiYmw7jVWqnEXO+Bi7iu7oJFjoLGAOzMoikrTQ29BW6tlvbGDASUDhZyZoiQLhmcWo0QrkoLxRLt3MCKEdnp+L6WXmrgRr6qPgR6zzTWhC/hHLsdLxXSb1u7oF8+8fC/tWJZliU8Yw/4lm5bPe+HA2ytAGkuKtExWzn6uhhIlMqk+T2fFdE4iduwNCydFaOXSfR/cwzxci9Qd1TQX7R1z+esJ3HtvFhGjfuWrGHOqH78TX75HsT/JCC/8Eb4FQUumSMli62xhjCQ5BdwilclTJQrKHiL5Nw+vkXe3zYYRUc42CqU7raGsjsG26LMc92VcQHcIkAb9CFZCcQbhVMIODwrHBIJp7k4hm/wKK6V9/iv7pyMB6YNzAhdH1sQUl8nTBmZBLNhKtMbTSnYNu9/0aNVNjGqVD70JrrBUf8q0cx6QHwDJkWNVqDs
    ASAAS_WEBHOOK_AUTH_TOKEN: AgB/jRLpa4uDa7nLWMfL3j5wXYPhAgoVLBwE2nHm5pphJwyYTLlOPzsI1Dylbr79ftlnxRTymHYPo3VeNr2+S5+6pmzVpzDwaFW91DvieRMaxhR0EYeVdcgZnlBRPDwdn9zukS+4HzVV5+ui4dkPYAhphUUOdThf1rm2vdk/rez87dJS9qU/DttTEJL9MlNM72aOE8tfL0h9zoO1+UhCIuGRcEnQJFVxZsHAhd5m2cwAFWjAwtrVNRNENw4BQtfFSmWWojeuJbfJB+QUjO5+CLYFS6F12PRWy/leuvPqdO4CPQt2ulA/0446LngSQcVcZU0ELWtJRWk1B/Im+iPeFDXd+uY9usTS6kfaU/i8i9NFQI8rR7GqRb7cmn4VHQgpcMSzs7xmyGUBLY1gwmCvvVsxlLqF7SLwnQNrep+JlcwHOpjlp42l25V42aHTwShd8CZHmbotoZXRJzk7flNobwXDBM6j17QX/LD4crzYFh6r6r5CGvPaZg/UPC8xfY/eTAaE8SYu7Vbrb8ID/AdrW/IG4zilxYZSWCupb3GLldg9TBVJhixqh5poauNJ9aE7nL2uNom73lCBkd3yz22OmJJ0R7Hs1jeuKNMPGUni8Zy8RJxZVXCeJHCGKTN2ivowdwCzc3MN/di2giVRZr4xZybz4Zgo1xnAp4roeemGDhSUIA4ByFwxXJUwKTXizFYXWDvHtdLG4C/HgdJar+NGxpRKYO4QDuqZG8MN4u8P3gZrl4F2iY2vzkVo3JZvRWCORFNu4kHeuW1MVAyNVREBo/fy
  template:
    metadata:
      creationTimestamp: null
      name: capoaberto-asaas
      namespace: capoaberto
    type: Opaque
