---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull
  namespace: capoaberto
spec:
  encryptedData:
    .dockerconfigjson: AgAuWOaUNak6JsmkCUDMEwEssCUNEQ5Ux+/L3WFd61uLIFjsudNrUDohmzpoGh5Ms975LEYMX8fdhcC7vrlmoY/jaR3GOz+KC1CqiE3W6rAlaTbFNSRRkOaBSaPfuSvH9UDY6m+PHscCsJnj5MpPXMlFRifFAWoNZBjMfeCkOFU6pSlGRkTpWZXs+DCavzeVxh7o3zuT+QvZIxHKcHrP/BififB7SSPtIAPsUcvhAEj/i0rHd3EFB7ueeb8MzzHZGb+QjnUUmq1yJbBokDYpxgeTpylDl2pnnM7KdVmrTL0xlMMC0//LeJTw9QKaS0/qj//pY90VVyHBl/mK8c9o1ZMLaVNOWDt8nzIYlFJEtFY3AfAWT7phMeFRh930i0GuTX0f7mMArgMaE1TuUdVGcOkCI2xr8vCmygRnqn7dha4lCg8t0lpv0rWQpG4dXOOsSnoXac5pGl33+lfa/UKWZWzQe3YoLPhQw2FVn/W7h7qNuX+CS4XrVKHoTebFQtkQNuW49IYybwhvH5IELX22jB39DGJTJBGK3bOtytBsHMlq8XaYXBqcxA6uoaK3RZl+TYAqxlWNiWmBh7zqarNLg7l5nER91xTBPwP6v8VUw5uyepnRLAoU+14MPIxiqzBLe6YbxEUUWITyBMGG6kTlNWkz+ODs7i3/ZPksmERnGUN4E5frF1tjrR7XqX3kXHZxaPSLOBcCTP4zUXTzEnSB25YzAdxaAnvJWj7oQGboR7l9bj4Pl9VlBXQ70wXMyUGiemE6y86wjuzqRaX4ry719j5pHXCmngjzgoNJCuMwKecFhtY9xaO5aupRfNXbIGoaL0AXaejpUj00jiv/OwmWPZ9yMvMCPuxEEGzCOePzMCJmH0Aufhx3GtgWOpSpYQ7Xmyy8Y9SS3YKF4Zc+nTS2zHV3ws1NwWZb3ZEogNURj8f3a/Nopw==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull
      namespace: capoaberto
    type: kubernetes.io/dockerconfigjson
