---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: opensandbox-api-key
  namespace: opensandbox-system
spec:
  encryptedData:
    api-key: AgDcHmIIbBmH06yrTsHcJKrW/OlN3kOFBCzpgSFJ/RMkFbaiItD2rt+rvkEIhVZKnwOJN9X6Kk+MeH13OMdE7WprYw2k3nUEbMKmu3BXyOcUT9mViLUchlRR9o91uNDid2sG2V1O+97c2sIZwJ1khINwG33B15suuozICi6RAODB/Zj6p5ygX3eSWYLaMYVL94/3RXcxwtr96V/wA6R6nd6B72BhjiNlMeFSPjdT5OmfLEIs31iv9LMfiL93HJBEZS2xoZWIVp2g50pB/pHlfvWpTPsn4nmLp2An0baoM2+w1QQWdzDeWiz7MSaJiUJ1JhZC+mMOekzItsVWOdUrgBrwbyirnsFuI1+gFllWVJ1CSIWsT6pnIgotvrDcrEXEPnt7vN7eqhl3n2VksfSw+gJMPQOT+nabO04N4fLtJhYSUAfwX2K/Wx8Ynd4Km8t9P5dvQj6hvWp75oQUSxZQRkLKcsHkMxvIhuMLsbFsn7OBfNK7FOqFjEXpbZ/YISD8GnP728Cx3buxpFgnpMc3cdAYPSbGBpdMqI716qCYFr6k6nAyvFXuTekW47osPKe2Lfk75u5Qt/T4Ycq3RuicPJwgonyxKqutPRzWM1gLHdOMegkuAmFZDrt0/Cqt6K6OyUVa6TiMdnCNg6cQkMea4pvQm/MpsSM+r6+/yyIYWjzGgWSEcby1qcEq3k1jqf31kf39LNM8MZH89NgoCy/R6Vn0kktQa2KgeoJEOujfjyKQ2m8KyxTgivWijfDeNA==
  template:
    metadata:
      name: opensandbox-api-key
      namespace: opensandbox-system